name: "Build"
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: cachix/cachix-action@v12
        with:
          name: st8ed-oss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build
        run: |
          echo "::group::Building images"
          nix build .#ci.images
          echo "::endgroup::"

          echo "::group::Building charts"
          nix build .#ci.charts
          echo "::endgroup::"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        run: |
          echo "::group::Publishing images"
          nix run .#ci.publish docker.io
          echo "::endgroup::"

          nix run .#ci.print-digests >>GITHUB_STEP_SUMMARY
